// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.2
// source: diamond/diamond.proto

package diamond

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DiamondClient is the client API for Diamond service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiamondClient interface {
	Add(ctx context.Context, in *UserDiamond, opts ...grpc.CallOption) (*Result, error)
}

type diamondClient struct {
	cc grpc.ClientConnInterface
}

func NewDiamondClient(cc grpc.ClientConnInterface) DiamondClient {
	return &diamondClient{cc}
}

func (c *diamondClient) Add(ctx context.Context, in *UserDiamond, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/Diamond/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiamondServer is the server API for Diamond service.
// All implementations must embed UnimplementedDiamondServer
// for forward compatibility
type DiamondServer interface {
	Add(context.Context, *UserDiamond) (*Result, error)
	mustEmbedUnimplementedDiamondServer()
}

// UnimplementedDiamondServer must be embedded to have forward compatible implementations.
type UnimplementedDiamondServer struct {
}

func (UnimplementedDiamondServer) Add(context.Context, *UserDiamond) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedDiamondServer) mustEmbedUnimplementedDiamondServer() {}

// UnsafeDiamondServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiamondServer will
// result in compilation errors.
type UnsafeDiamondServer interface {
	mustEmbedUnimplementedDiamondServer()
}

func RegisterDiamondServer(s grpc.ServiceRegistrar, srv DiamondServer) {
	s.RegisterService(&Diamond_ServiceDesc, srv)
}

func _Diamond_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserDiamond)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiamondServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Diamond/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiamondServer).Add(ctx, req.(*UserDiamond))
	}
	return interceptor(ctx, in, info, handler)
}

// Diamond_ServiceDesc is the grpc.ServiceDesc for Diamond service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Diamond_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Diamond",
	HandlerType: (*DiamondServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Diamond_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "diamond/diamond.proto",
}
